/**
 * HtmlOBD - Catálogo Completo de Vehículos de Argentina & Decodificador VIN
 * Base de datos exhaustiva de marcas y modelos del mercado automotor argentino.
 */

export const ARGENTINA_BRANDS = [
  'Toyota',
  'Volkswagen',
  'Fiat',
  'Peugeot',
  'Ford',
  'Chevrolet',
  'Renault',
  'Citroën',
  'Jeep / RAM',
  'Nissan',
  'Honda',
  'Audi / BMW / Mercedes'
];

export const ARGENTINA_VEHICLES = [
  // ===================== TOYOTA =====================
  {
    id: 'toyota_hilux_28',
    brand: 'Toyota',
    model: 'Hilux 2.8 D-4D Turbodiésel',
    year: 2024,
    engine: '2.8L Turbodiésel 1GD-FTV',
    fuelType: 'Diésel',
    powerHp: 204,
    torqueNm: 500,
    weightKg: 2090,
    displacementCc: 2755,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8AJ',
    description: 'Fabricada en Planta Zárate, Buenos Aires. La pick-up líder del mercado.'
  },
  {
    id: 'toyota_hilux_24',
    brand: 'Toyota',
    model: 'Hilux 2.4 D-4D Turbodiésel',
    year: 2023,
    engine: '2.4L Turbodiésel 2GD-FTV',
    fuelType: 'Diésel',
    powerHp: 150,
    torqueNm: 400,
    weightKg: 1980,
    displacementCc: 2393,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8AJ',
    description: 'Versión de trabajo estándar fabricada en Planta Zárate.'
  },
  {
    id: 'toyota_sw4_28',
    brand: 'Toyota',
    model: 'SW4 / Fortuner 2.8 D-4D',
    year: 2024,
    engine: '2.8L Turbodiésel 1GD-FTV',
    fuelType: 'Diésel',
    powerHp: 204,
    torqueNm: 500,
    weightKg: 2185,
    displacementCc: 2755,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8AJ',
    description: 'SUV de 7 asientos basada en Hilux fabricada en Zárate.'
  },
  {
    id: 'toyota_corolla_20',
    brand: 'Toyota',
    model: 'Corolla 2.0 Dynamic Force',
    year: 2023,
    engine: '2.0L Dual VVT-iE (M20A-FKS)',
    fuelType: 'Nafta',
    powerHp: 170,
    torqueNm: 200,
    weightKg: 1350,
    displacementCc: 1987,
    redlineRpm: 6600,
    maxGaugeRpm: 8000,
    vinPrefix: '9BR',
    description: 'Sedán mediano importado de Brasil (Indaiatuba).'
  },
  {
    id: 'toyota_corolla_hybrid',
    brand: 'Toyota',
    model: 'Corolla 1.8 Hybrid',
    year: 2023,
    engine: '1.8L Atkinson + Motor Eléctrico',
    fuelType: 'Híbrido',
    powerHp: 122,
    torqueNm: 142,
    weightKg: 1410,
    displacementCc: 1798,
    redlineRpm: 5600,
    maxGaugeRpm: 8000,
    vinPrefix: '9BR',
    description: 'Sedán híbrido auto-recargable de alta eficiencia.'
  },
  {
    id: 'toyota_corolla_cross',
    brand: 'Toyota',
    model: 'Corolla Cross 2.0 / 1.8 Hybrid',
    year: 2024,
    engine: '2.0L 170 CV / 1.8 Híbrido',
    fuelType: 'Nafta / Híbrido',
    powerHp: 170,
    torqueNm: 200,
    weightKg: 1420,
    displacementCc: 1987,
    redlineRpm: 6600,
    maxGaugeRpm: 8000,
    vinPrefix: '9BR',
    description: 'SUV del segmento C más vendida de la región (Sorocaba).'
  },
  {
    id: 'toyota_yaris_15',
    brand: 'Toyota',
    model: 'Yaris 1.5 Dual VVT-i',
    year: 2023,
    engine: '1.5L 16V Dual VVT-i (2NR-FE)',
    fuelType: 'Nafta',
    powerHp: 107,
    torqueNm: 140,
    weightKg: 1110,
    displacementCc: 1496,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '9BR',
    description: 'Hatchback y sedán segmento B producido en Brasil.'
  },
  {
    id: 'toyota_etios_15',
    brand: 'Toyota',
    model: 'Etios 1.5 Dual VVT-i',
    year: 2021,
    engine: '1.5L 16V Dual VVT-i (2NR-FBE)',
    fuelType: 'Nafta',
    powerHp: 103,
    torqueNm: 137,
    weightKg: 1020,
    displacementCc: 1496,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '9BR',
    description: 'Referente histórico por confiabilidad y bajo costo de mantenimiento.'
  },

  // ===================== VOLKSWAGEN =====================
  {
    id: 'vw_amarok_v6',
    brand: 'Volkswagen',
    model: 'Amarok 3.0 V6 TDI',
    year: 2024,
    engine: '3.0L V6 Turbodiésel (EA897)',
    fuelType: 'Diésel',
    powerHp: 258,
    torqueNm: 580,
    weightKg: 2185,
    displacementCc: 2967,
    redlineRpm: 4600,
    maxGaugeRpm: 6000,
    vinPrefix: '8AW',
    description: 'Fabricada en Centro Industrial Pacheco, Bs. As. Máxima potencia en pick-ups.'
  },
  {
    id: 'vw_amarok_20',
    brand: 'Volkswagen',
    model: 'Amarok 2.0 BiTDI / TDI',
    year: 2022,
    engine: '2.0L Bi-Turbodiésel 180 CV',
    fuelType: 'Diésel',
    powerHp: 180,
    torqueNm: 420,
    weightKg: 2060,
    displacementCc: 1968,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '8AW',
    description: 'Motor 2.0 turbodiésel fabricado en Pacheco.'
  },
  {
    id: 'vw_taos_14t',
    brand: 'Volkswagen',
    model: 'Taos 1.4 250 TSI',
    year: 2024,
    engine: '1.4L TSI Turbo Intercooler (EA211)',
    fuelType: 'Nafta',
    powerHp: 150,
    torqueNm: 250,
    weightKg: 1420,
    displacementCc: 1395,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AW',
    description: 'SUV mediana de producción nacional fabricada en Pacheco.'
  },
  {
    id: 'vw_golf_14t',
    brand: 'Volkswagen',
    model: 'Golf VII 1.4 TSI / 2.0 GTI',
    year: 2019,
    engine: '1.4L TSI 150 CV / 2.0 TSI GTI 230 CV',
    fuelType: 'Nafta',
    powerHp: 150,
    torqueNm: 250,
    weightKg: 1290,
    displacementCc: 1395,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '3VW',
    description: 'Referente indiscutido del segmento C en Argentina (Importado de México).'
  },
  {
    id: 'vw_vento_gli',
    brand: 'Volkswagen',
    model: 'Vento / Jetta 2.0 TSI GLI / 1.4T',
    year: 2023,
    engine: '2.0L TSI 230 CV (EA888 Gen 3)',
    fuelType: 'Nafta',
    powerHp: 230,
    torqueNm: 350,
    weightKg: 1445,
    displacementCc: 1984,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: '3VW',
    description: 'Sedán deportivo turbo clásico de alta demanda.'
  },
  {
    id: 'vw_polo_16',
    brand: 'Volkswagen',
    model: 'Polo / Virtus 1.6 MSI / 1.0 TSI',
    year: 2023,
    engine: '1.6L 16V 110 CV / 1.0T 200 TSI',
    fuelType: 'Nafta',
    powerHp: 110,
    torqueNm: 155,
    weightKg: 1120,
    displacementCc: 1598,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '9BW',
    description: 'Plataforma MQB-A0 brasileña para el segmento B.'
  },
  {
    id: 'vw_gol_trend',
    brand: 'Volkswagen',
    model: 'Gol Trend 1.6 8V',
    year: 2020,
    engine: '1.6L 8V EA111',
    fuelType: 'Nafta',
    powerHp: 101,
    torqueNm: 143,
    weightKg: 1030,
    displacementCc: 1598,
    redlineRpm: 5800,
    maxGaugeRpm: 8000,
    vinPrefix: '9BW',
    description: 'El vehículo más vendido de la historia automotriz argentina por 17 años.'
  },
  {
    id: 'vw_suran_16',
    brand: 'Volkswagen',
    model: 'Suran / Fox 1.6 8V / 16V',
    year: 2018,
    engine: '1.6L EA111 / MSI',
    fuelType: 'Nafta',
    powerHp: 101,
    torqueNm: 143,
    weightKg: 1200,
    displacementCc: 1598,
    redlineRpm: 5800,
    maxGaugeRpm: 8000,
    vinPrefix: '8AW',
    description: 'Familiar producida en General Pacheco hasta 2019.'
  },
  {
    id: 'vw_tcross_nivus',
    brand: 'Volkswagen',
    model: 'T-Cross / Nivus 1.0 200 TSI',
    year: 2024,
    engine: '1.0L Turbo 3 Cilindros (EA211)',
    fuelType: 'Nafta',
    powerHp: 116,
    torqueNm: 200,
    weightKg: 1240,
    displacementCc: 999,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '9BW',
    description: 'Crossovers urbanos con motorización turbo de 3 cilindros.'
  },

  // ===================== FIAT =====================
  {
    id: 'fiat_cronos_13',
    brand: 'Fiat',
    model: 'Cronos 1.3 FireFly',
    year: 2024,
    engine: '1.3L 8V FireFly (GSE N3)',
    fuelType: 'Nafta',
    powerHp: 99,
    torqueNm: 127,
    weightKg: 1140,
    displacementCc: 1332,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AP',
    description: 'Producido en Planta Ferreyra, Córdoba. Auto #1 en ventas de Argentina.'
  },
  {
    id: 'fiat_cronos_18',
    brand: 'Fiat',
    model: 'Cronos 1.8 E-TorQ Precision',
    year: 2021,
    engine: '1.8L 16V E-TorQ EVO',
    fuelType: 'Nafta',
    powerHp: 130,
    torqueNm: 182,
    weightKg: 1210,
    displacementCc: 1747,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '8AP',
    description: 'Versión de mayor cilindrada y potencia producida en Córdoba.'
  },
  {
    id: 'fiat_argo_13',
    brand: 'Fiat',
    model: 'Argo 1.3 FireFly / 1.8 HGT',
    year: 2022,
    engine: '1.3L FireFly / 1.8 E-TorQ',
    fuelType: 'Nafta',
    powerHp: 99,
    torqueNm: 127,
    weightKg: 1120,
    displacementCc: 1332,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '9BD',
    description: 'Hatchback hermano del Cronos producido en Betim, Brasil.'
  },
  {
    id: 'fiat_pulse_10t',
    brand: 'Fiat',
    model: 'Pulse 1.0 Turbo 200 / 1.3',
    year: 2024,
    engine: '1.0L Turbo T200 120 CV',
    fuelType: 'Nafta',
    powerHp: 120,
    torqueNm: 200,
    weightKg: 1190,
    displacementCc: 999,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '9BD',
    description: 'Crossover compacto moderno con motor GSE Turbo.'
  },
  {
    id: 'fiat_toro_20d',
    brand: 'Fiat',
    model: 'Toro 2.0 Multijet TD 4x4',
    year: 2023,
    engine: '2.0L Turbodiésel Multijet II',
    fuelType: 'Diésel',
    powerHp: 170,
    torqueNm: 350,
    weightKg: 1870,
    displacementCc: 1956,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '9BD',
    description: 'Pick-up compacta SUP fabricada en Pernambuco.'
  },
  {
    id: 'fiat_strada_13',
    brand: 'Fiat',
    model: 'Strada 1.3 FireFly / 1.4 Fire',
    year: 2023,
    engine: '1.3L FireFly 99 CV',
    fuelType: 'Nafta',
    powerHp: 99,
    torqueNm: 127,
    weightKg: 1150,
    displacementCc: 1332,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '9BD',
    description: 'Líder histórica de utilitarios livianos urbanos.'
  },
  {
    id: 'fiat_palio_siena',
    brand: 'Fiat',
    model: 'Palio / Siena 1.4 Fire / 1.6',
    year: 2017,
    engine: '1.4L 8V Fire 87 CV',
    fuelType: 'Nafta',
    powerHp: 87,
    torqueNm: 124,
    weightKg: 1040,
    displacementCc: 1368,
    redlineRpm: 5800,
    maxGaugeRpm: 8000,
    vinPrefix: '8AP',
    description: 'Vehículo histórico producido en la planta de Ferreyra, Córdoba.'
  },

  // ===================== PEUGEOT =====================
  {
    id: 'peugeot_208_16',
    brand: 'Peugeot',
    model: '208 1.6 VTi (El Palomar)',
    year: 2024,
    engine: '1.6L 16V VTi (EC5)',
    fuelType: 'Nafta',
    powerHp: 115,
    torqueNm: 150,
    weightKg: 1155,
    displacementCc: 1587,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Fabricado en Planta El Palomar, Bs. As. Plataforma CMP.'
  },
  {
    id: 'peugeot_208_t200',
    brand: 'Peugeot',
    model: '208 1.0 Turbo T200',
    year: 2024,
    engine: '1.0L Turbo 3 Cil. T200',
    fuelType: 'Nafta',
    powerHp: 120,
    torqueNm: 200,
    weightKg: 1180,
    displacementCc: 999,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Nueva motorización turbo producida en El Palomar.'
  },
  {
    id: 'peugeot_2008_16thp',
    brand: 'Peugeot',
    model: '2008 II 1.0T / 1.6 THP',
    year: 2024,
    engine: '1.0L Turbo T200 / 1.6 THP 165 CV',
    fuelType: 'Nafta',
    powerHp: 165,
    torqueNm: 240,
    weightKg: 1260,
    displacementCc: 1598,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Nueva generación producida en El Palomar para toda la región.'
  },
  {
    id: 'peugeot_308_408_thp',
    brand: 'Peugeot',
    model: '308 / 408 1.6 THP / 2.0 16V',
    year: 2019,
    engine: '1.6L Turbo THP EP6CDT 163 CV',
    fuelType: 'Nafta',
    powerHp: 163,
    torqueNm: 240,
    weightKg: 1390,
    displacementCc: 1598,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Hatchback y sedán medianos de gran arraigo fabricados en El Palomar.'
  },
  {
    id: 'peugeot_partner_hdi',
    brand: 'Peugeot',
    model: 'Partner 1.6 HDi / 1.6 VTi',
    year: 2023,
    engine: '1.6L Turbodiésel HDi DV6D',
    fuelType: 'Diésel',
    powerHp: 92,
    torqueNm: 215,
    weightKg: 1280,
    displacementCc: 1560,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '8AD',
    description: 'Furgón utilitario nacional insignia de El Palomar.'
  },
  {
    id: 'peugeot_206_207',
    brand: 'Peugeot',
    model: '206 / 207 Compact 1.4 / 1.6 / 1.9D',
    year: 2012,
    engine: '1.4L TU3JP / 1.6 16V TU5JP4 / 1.9D',
    fuelType: 'Nafta / Diésel',
    powerHp: 110,
    torqueNm: 147,
    weightKg: 1040,
    displacementCc: 1587,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Vehículo histórico récord de ventas fabricado en El Palomar.'
  },

  // ===================== FORD =====================
  {
    id: 'ford_ranger_v6',
    brand: 'Ford',
    model: 'Ranger 3.0 V6 EcoBlue',
    year: 2024,
    engine: '3.0L V6 Turbodiésel EcoBlue (Lion)',
    fuelType: 'Diésel',
    powerHp: 250,
    torqueNm: 600,
    weightKg: 2280,
    displacementCc: 2993,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '8AF',
    description: 'Fabricada en Planta Pacheco tras inversión récord de 660 millones de USD.'
  },
  {
    id: 'ford_ranger_20bi',
    brand: 'Ford',
    model: 'Ranger 2.0 Bi-Turbo EcoBlue',
    year: 2024,
    engine: '2.0L 4 Cil. Bi-Turbodiésel Panther',
    fuelType: 'Diésel',
    powerHp: 210,
    torqueNm: 500,
    weightKg: 2160,
    displacementCc: 1996,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '8AF',
    description: 'Nueva generación 2.0 Bi-Turbo nacional fabricada en Pacheco.'
  },
  {
    id: 'ford_ranger_32',
    brand: 'Ford',
    model: 'Ranger 3.2 TDCi Puma 5 Cilindros',
    year: 2022,
    engine: '3.2L 5 Cil. Turbodiésel Duratorq',
    fuelType: 'Diésel',
    powerHp: 200,
    torqueNm: 470,
    weightKg: 2150,
    displacementCc: 3198,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8AF',
    description: 'Emblemático motor de 5 cilindros diésel nacional.'
  },
  {
    id: 'ford_focus_3_20',
    brand: 'Ford',
    model: 'Focus III 2.0 Duratec GDI',
    year: 2019,
    engine: '2.0L Inyección Directa Ti-VCT',
    fuelType: 'Nafta',
    powerHp: 170,
    torqueNm: 202,
    weightKg: 1360,
    displacementCc: 1999,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: '8AF',
    description: 'Producido en Pacheco hasta 2019. Dinámica y tecnología referente de segmento.'
  },
  {
    id: 'ford_focus_3_16',
    brand: 'Ford',
    model: 'Focus III 1.6 Sigma Ti-VCT',
    year: 2018,
    engine: '1.6L 16V Sigma',
    fuelType: 'Nafta',
    powerHp: 125,
    torqueNm: 159,
    weightKg: 1290,
    displacementCc: 1596,
    redlineRpm: 6300,
    maxGaugeRpm: 8000,
    vinPrefix: '8AF',
    description: 'Versión 1.6 de entrada de gama del Focus nacional.'
  },
  {
    id: 'ford_fiesta_kd',
    brand: 'Ford',
    model: 'Fiesta Kinetic Design 1.6 Ti-VCT',
    year: 2018,
    engine: '1.6L 16V Sigma 120 CV',
    fuelType: 'Nafta',
    powerHp: 120,
    torqueNm: 152,
    weightKg: 1140,
    displacementCc: 1596,
    redlineRpm: 6300,
    maxGaugeRpm: 8000,
    vinPrefix: '3FA',
    description: 'Hatchback del segmento B histórico referente en seguridad.'
  },
  {
    id: 'ford_ecosport_15_20',
    brand: 'Ford',
    model: 'EcoSport 1.5 Dragon / 2.0 Duratec',
    year: 2021,
    engine: '1.5L 3 Cil. Dragon 123 CV / 2.0 GDI',
    fuelType: 'Nafta',
    powerHp: 123,
    torqueNm: 151,
    weightKg: 1270,
    displacementCc: 1497,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: '9BF',
    description: 'La creadora del segmento de SUV compactas en el Mercosur.'
  },
  {
    id: 'ford_maverick_20t',
    brand: 'Ford',
    model: 'Maverick 2.0 EcoBoost / Hybrid',
    year: 2024,
    engine: '2.0L EcoBoost Turbo 253 CV',
    fuelType: 'Nafta',
    powerHp: 253,
    torqueNm: 380,
    weightKg: 1720,
    displacementCc: 1999,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '3FT',
    description: 'Pick-up compacta monocasco de altas prestaciones (México).'
  },

  // ===================== CHEVROLET =====================
  {
    id: 'chevrolet_cruze_14t',
    brand: 'Chevrolet',
    model: 'Cruze 1.4 Turbo Ecotec SIDI',
    year: 2023,
    engine: '1.4L Turbo con Inyección Directa',
    fuelType: 'Nafta',
    powerHp: 153,
    torqueNm: 245,
    weightKg: 1300,
    displacementCc: 1399,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AG',
    description: 'Fabricado en Complejo Alvear, Santa Fe. Referente nacional de calidad.'
  },
  {
    id: 'chevrolet_tracker_12t',
    brand: 'Chevrolet',
    model: 'Tracker 1.2 Turbo (Alvear)',
    year: 2024,
    engine: '1.2L 3 Cilindros Turbo (CSS Prime)',
    fuelType: 'Nafta',
    powerHp: 132,
    torqueNm: 190,
    weightKg: 1260,
    displacementCc: 1199,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AG',
    description: 'SUV compacta de producción nacional en la planta de Alvear, Santa Fe.'
  },
  {
    id: 'chevrolet_onix_10t',
    brand: 'Chevrolet',
    model: 'Onix / Onix Plus 1.0 Turbo',
    year: 2023,
    engine: '1.0L Turbo 3 Cilindros 116 CV',
    fuelType: 'Nafta',
    powerHp: 116,
    torqueNm: 160,
    weightKg: 1115,
    displacementCc: 999,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '9BG',
    description: 'Sedán y hatchback modernos con 6 airbags y WiFi integrado.'
  },
  {
    id: 'chevrolet_s10_28',
    brand: 'Chevrolet',
    model: 'S10 2.8 CTDI Turbodiésel',
    year: 2024,
    engine: '2.8L Duramax Turbodiésel 200 CV',
    fuelType: 'Diésel',
    powerHp: 200,
    torqueNm: 500,
    weightKg: 2100,
    displacementCc: 2776,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '9BG',
    description: 'Pick-up mediana clásica del campo argentino.'
  },
  {
    id: 'chevrolet_classic_corsa',
    brand: 'Chevrolet',
    model: 'Corsa / Classic 1.4 8V',
    year: 2016,
    engine: '1.4L 8V EconoFlex / 1.6 MPFI',
    fuelType: 'Nafta',
    powerHp: 92,
    torqueNm: 120,
    weightKg: 980,
    displacementCc: 1389,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AG',
    description: 'Más de 1.000.000 de unidades producidas en Alvear, Santa Fe.'
  },
  {
    id: 'chevrolet_spin_18',
    brand: 'Chevrolet',
    model: 'Spin 1.8 8V (5 / 7 Asientos)',
    year: 2023,
    engine: '1.8L 8V SPE/4 105 CV',
    fuelType: 'Nafta',
    powerHp: 105,
    torqueNm: 161,
    weightKg: 1280,
    displacementCc: 1796,
    redlineRpm: 5800,
    maxGaugeRpm: 8000,
    vinPrefix: '9BG',
    description: 'Monovolumen familiar clásico del Mercosur.'
  },

  // ===================== RENAULT =====================
  {
    id: 'renault_sandero_stepway',
    brand: 'Renault',
    model: 'Sandero / Stepway 1.6 SCe / 2.0 RS',
    year: 2023,
    engine: '1.6L 16V SCe 115 CV / 2.0 F4R 145 CV',
    fuelType: 'Nafta',
    powerHp: 115,
    torqueNm: 156,
    weightKg: 1140,
    displacementCc: 1598,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '8A1',
    description: 'Fabricado en Fábrica Santa Isabel, Córdoba.'
  },
  {
    id: 'renault_kangoo_2',
    brand: 'Renault',
    model: 'Kangoo II 1.6 SCe / 1.5 dCi',
    year: 2024,
    engine: '1.6L 16V SCe (H4M) / 1.5 dCi K9K',
    fuelType: 'Nafta / Diésel',
    powerHp: 114,
    torqueNm: 156,
    weightKg: 1260,
    displacementCc: 1598,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8A1',
    description: 'Utilitario líder histórico producido en Santa Isabel, Córdoba.'
  },
  {
    id: 'renault_duster_13t',
    brand: 'Renault',
    model: 'Duster 1.3 TCe Turbo 4x4 / 1.6',
    year: 2024,
    engine: '1.3L Turbo TCe 155 CV / 1.6 SCe',
    fuelType: 'Nafta',
    powerHp: 155,
    torqueNm: 250,
    weightKg: 1350,
    displacementCc: 1332,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '93Y',
    description: 'SUV con tracción 4x4 y motor turbo desarrollado junto a Mercedes-Benz.'
  },
  {
    id: 'renault_alaskan_23',
    brand: 'Renault',
    model: 'Alaskan 2.3 dCi Bi-Turbo 190 CV',
    year: 2023,
    engine: '2.3L Bi-Turbodiésel M9T',
    fuelType: 'Diésel',
    powerHp: 190,
    torqueNm: 450,
    weightKg: 2130,
    displacementCc: 2298,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8A1',
    description: 'Pick-up mediana fabricada en Santa Isabel, Córdoba.'
  },
  {
    id: 'renault_oroch_13t',
    brand: 'Renault',
    model: 'Oroch 1.3 TCe Turbo / 1.6',
    year: 2023,
    engine: '1.3L Turbo TCe 162 CV',
    fuelType: 'Nafta',
    powerHp: 162,
    torqueNm: 270,
    weightKg: 1430,
    displacementCc: 1332,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '93Y',
    description: 'Pick-up compacta doble cabina.'
  },
  {
    id: 'renault_clio_mio',
    brand: 'Renault',
    model: 'Clio 2 / Clio Mio 1.2 16V',
    year: 2016,
    engine: '1.2L 16V D4F 75 CV',
    fuelType: 'Nafta',
    powerHp: 75,
    torqueNm: 105,
    weightKg: 910,
    displacementCc: 1149,
    redlineRpm: 5800,
    maxGaugeRpm: 8000,
    vinPrefix: '8A1',
    description: 'Más de 500.000 unidades producidas en Santa Isabel.'
  },
  {
    id: 'renault_fluence_20',
    brand: 'Renault',
    model: 'Fluence 2.0 16V / 2.0 Turbo GT',
    year: 2018,
    engine: '2.0L M4R 143 CV / 2.0T F4Rt 190 CV',
    fuelType: 'Nafta',
    powerHp: 143,
    torqueNm: 195,
    weightKg: 1370,
    displacementCc: 1997,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '8A1',
    description: 'Sedán del segmento C fabricado en Santa Isabel.'
  },

  // ===================== CITROËN =====================
  {
    id: 'citroen_c3_12_16',
    brand: 'Citroën',
    model: 'C3 1.2 PureTech / 1.6 VTi / 1.0T',
    year: 2024,
    engine: '1.6L VTi 115 CV / 1.0 FireFly',
    fuelType: 'Nafta',
    powerHp: 115,
    torqueNm: 150,
    weightKg: 1120,
    displacementCc: 1587,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '936',
    description: 'Hatchback accesible del grupo Stellantis producido en Porto Real.'
  },
  {
    id: 'citroen_c4_cactus',
    brand: 'Citroën',
    model: 'C4 Cactus 1.6 THP / 1.6 VTi',
    year: 2023,
    engine: '1.6L THP Turbo 165 CV (EP6)',
    fuelType: 'Nafta',
    powerHp: 165,
    torqueNm: 240,
    weightKg: 1225,
    displacementCc: 1598,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '936',
    description: 'Crossover con una de las mejores relaciones peso/potencia de su clase.'
  },
  {
    id: 'citroen_berlingo_hdi',
    brand: 'Citroën',
    model: 'Berlingo 1.6 HDi / 1.6 VTi',
    year: 2023,
    engine: '1.6L Turbodiésel HDi DV6D',
    fuelType: 'Diésel',
    powerHp: 92,
    torqueNm: 215,
    weightKg: 1280,
    displacementCc: 1560,
    redlineRpm: 4500,
    maxGaugeRpm: 6000,
    vinPrefix: '8AD',
    description: 'Producida en Planta El Palomar, Buenos Aires.'
  },
  {
    id: 'citroen_c4_lounge',
    brand: 'Citroën',
    model: 'C4 Lounge 1.6 THP / 2.0 / HDi',
    year: 2019,
    engine: '1.6L Turbo THP 165 CV',
    fuelType: 'Nafta',
    powerHp: 165,
    torqueNm: 240,
    weightKg: 1380,
    displacementCc: 1598,
    redlineRpm: 6000,
    maxGaugeRpm: 8000,
    vinPrefix: '8AD',
    description: 'Sedán mediano de confort superior fabricado en El Palomar.'
  },

  // ===================== JEEP / RAM =====================
  {
    id: 'jeep_renegade_18_13t',
    brand: 'Jeep / RAM',
    model: 'Jeep Renegade 1.3 Turbo T270 / 1.8',
    year: 2024,
    engine: '1.3L Turbo T270 175 CV (GSE)',
    fuelType: 'Nafta',
    powerHp: 175,
    torqueNm: 270,
    weightKg: 1450,
    displacementCc: 1332,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '988',
    description: 'SUV compacta icono del grupo Stellantis producida en Pernambuco.'
  },
  {
    id: 'jeep_compass_t270',
    brand: 'Jeep / RAM',
    model: 'Jeep Compass 1.3 Turbo T270 / 2.0 TD',
    year: 2024,
    engine: '1.3L Turbo 175 CV / 2.0 Multijet TD 170 CV',
    fuelType: 'Nafta / Diésel',
    powerHp: 175,
    torqueNm: 270,
    weightKg: 1580,
    displacementCc: 1332,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '988',
    description: 'SUV del segmento C líder indiscutido en la región.'
  },
  {
    id: 'ram_rampage_20t',
    brand: 'Jeep / RAM',
    model: 'RAM Rampage 2.0 Turbo Hurricane 4',
    year: 2024,
    engine: '2.0L 4 Cil. Turbo Hurricane 4 272 CV',
    fuelType: 'Nafta',
    powerHp: 272,
    torqueNm: 400,
    weightKg: 1910,
    displacementCc: 1995,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: '988',
    description: 'Pick-up compacta más potente fabricada en Sudamérica.'
  },

  // ===================== NISSAN =====================
  {
    id: 'nissan_frontier_23',
    brand: 'Nissan',
    model: 'Frontier 2.3 Bi-Turbo Diésel',
    year: 2024,
    engine: '2.3L Bi-Turbodiésel YS23DDT',
    fuelType: 'Diésel',
    powerHp: 190,
    torqueNm: 450,
    weightKg: 2125,
    displacementCc: 2298,
    redlineRpm: 4400,
    maxGaugeRpm: 6000,
    vinPrefix: '8AT',
    description: 'Fabricada en Santa Isabel, Córdoba. Suspensión multilink trasera única en su clase.'
  },
  {
    id: 'nissan_kicks_16',
    brand: 'Nissan',
    model: 'Kicks 1.6 16V',
    year: 2023,
    engine: '1.6L 16V HR16DE 120 CV',
    fuelType: 'Nafta',
    powerHp: 120,
    torqueNm: 149,
    weightKg: 1140,
    displacementCc: 1598,
    redlineRpm: 6300,
    maxGaugeRpm: 8000,
    vinPrefix: '94D',
    description: 'Crossover urbano de gran confiabilidad (Resende, Brasil).'
  },
  {
    id: 'nissan_versa_sentra',
    brand: 'Nissan',
    model: 'Versa 1.6 / Sentra 2.0',
    year: 2023,
    engine: '1.6L 118 CV / 2.0 MR20DD 147 CV',
    fuelType: 'Nafta',
    powerHp: 147,
    torqueNm: 197,
    weightKg: 1360,
    displacementCc: 1997,
    redlineRpm: 6400,
    maxGaugeRpm: 8000,
    vinPrefix: '3N1',
    description: 'Sedanes del segmento B y C producidos en Aguascalientes, México.'
  },

  // ===================== HONDA =====================
  {
    id: 'honda_hrv_15t',
    brand: 'Honda',
    model: 'HR-V 1.5 Turbo / 1.8 i-VTEC',
    year: 2024,
    engine: '1.5L VTEC Turbo 177 CV / 1.8 R18Z9',
    fuelType: 'Nafta',
    powerHp: 177,
    torqueNm: 240,
    weightKg: 1380,
    displacementCc: 1498,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: '8A7',
    description: 'Histórica producción en Planta Campana, Bs. As. (Hoy importada).'
  },
  {
    id: 'honda_civic_20_15t',
    brand: 'Honda',
    model: 'Civic 2.0 i-VTEC / 1.5 Turbo',
    year: 2021,
    engine: '1.5L Turbo L15B7 173 CV / 2.0 K20C2',
    fuelType: 'Nafta',
    powerHp: 173,
    torqueNm: 220,
    weightKg: 1320,
    displacementCc: 1498,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: '93H',
    description: 'Sedán legendario del segmento C producido en Sumaré, Brasil.'
  },
  {
    id: 'honda_fit_city',
    brand: 'Honda',
    model: 'Fit / City 1.5 i-VTEC',
    year: 2019,
    engine: '1.5L 16V i-VTEC (L15Z)',
    fuelType: 'Nafta',
    powerHp: 120,
    torqueNm: 145,
    weightKg: 1080,
    displacementCc: 1497,
    redlineRpm: 6600,
    maxGaugeRpm: 8000,
    vinPrefix: '8A7',
    description: 'City fabricado en Campana y Fit en Brasil. Máxima habitabilidad.'
  },

  // ===================== AUDI / BMW / MERCEDES =====================
  {
    id: 'audi_a3_a4_tfsi',
    brand: 'Audi / BMW / Mercedes',
    model: 'Audi A3 / A4 2.0 TFSI (EA888)',
    year: 2022,
    engine: '2.0L TFSI Turbo 190 / 252 CV',
    fuelType: 'Nafta',
    powerHp: 190,
    torqueNm: 320,
    weightKg: 1460,
    displacementCc: 1984,
    redlineRpm: 6500,
    maxGaugeRpm: 8000,
    vinPrefix: 'WAU',
    description: 'Sedán y hatchback premium de amplia presencia en Argentina.'
  },
  {
    id: 'bmw_320i_330i_f30',
    brand: 'Audi / BMW / Mercedes',
    model: 'BMW Serie 3 320i / 330i (F30 / G20)',
    year: 2022,
    engine: '2.0L TwinPower Turbo (B48) 258 CV',
    fuelType: 'Nafta',
    powerHp: 258,
    torqueNm: 400,
    weightKg: 1540,
    displacementCc: 1998,
    redlineRpm: 6800,
    maxGaugeRpm: 8000,
    vinPrefix: 'WBA',
    description: 'Sedán deportivo premium de tracción trasera referente en el país.'
  },
  {
    id: 'mercedes_sprinter_cdi',
    brand: 'Audi / BMW / Mercedes',
    model: 'Mercedes-Benz Sprinter 2.1 CDI',
    year: 2024,
    engine: '2.1L Turbodiésel OM651 163 CV',
    fuelType: 'Diésel',
    powerHp: 163,
    torqueNm: 360,
    weightKg: 2450,
    displacementCc: 2143,
    redlineRpm: 4200,
    maxGaugeRpm: 5000,
    vinPrefix: '8AC',
    description: 'Fabricada en Centro Industrial Juan Manuel Fangio, Virrey del Pino, Bs. As.'
  },
  {
    id: 'mercedes_clase_a_c',
    brand: 'Audi / BMW / Mercedes',
    model: 'Mercedes-Benz Clase A 200 / C 200',
    year: 2022,
    engine: '1.3L Turbo 163 CV / 2.0L Turbo 204 CV',
    fuelType: 'Nafta',
    powerHp: 163,
    torqueNm: 250,
    weightKg: 1375,
    displacementCc: 1332,
    redlineRpm: 6200,
    maxGaugeRpm: 8000,
    vinPrefix: 'WDD',
    description: 'Gama compacta y mediana de la estrella en Argentina.'
  }
];

// Tabla de decodificación de WMI (País y Fabricante)
const WMI_TABLE = {
  '8AJ': { country: 'Argentina', brand: 'Toyota', plant: 'Zárate, Bs. As.' },
  '8AF': { country: 'Argentina', brand: 'Ford', plant: 'Gral. Pacheco, Bs. As.' },
  '8AW': { country: 'Argentina', brand: 'Volkswagen', plant: 'Gral. Pacheco, Bs. As.' },
  '8AG': { country: 'Argentina', brand: 'General Motors', plant: 'Alvear, Santa Fe' },
  '8AD': { country: 'Argentina', brand: 'Peugeot / Citroën', plant: 'El Palomar, Bs. As.' },
  '8AP': { country: 'Argentina', brand: 'Fiat / Stellantis', plant: 'Ferreyra, Córdoba' },
  '8A1': { country: 'Argentina', brand: 'Renault', plant: 'Santa Isabel, Córdoba' },
  '8AT': { country: 'Argentina', brand: 'Nissan', plant: 'Santa Isabel, Córdoba' },
  '8A7': { country: 'Argentina', brand: 'Honda', plant: 'Campana, Bs. As.' },
  '8AC': { country: 'Argentina', brand: 'Mercedes-Benz', plant: 'Virrey del Pino, Bs. As.' },
  '9BW': { country: 'Brasil', brand: 'Volkswagen', plant: 'São Bernardo do Campo' },
  '9BR': { country: 'Brasil', brand: 'Toyota', plant: 'Indaiatuba / Sorocaba' },
  '9BD': { country: 'Brasil', brand: 'Fiat', plant: 'Betim, Minas Gerais' },
  '9BG': { country: 'Brasil', brand: 'General Motors', plant: 'São Caetano / Gravataí' },
  '93Y': { country: 'Brasil', brand: 'Renault', plant: 'São José dos Pinhais' },
  '936': { country: 'Brasil', brand: 'Citroën / Peugeot', plant: 'Porto Real, RJ' },
  '988': { country: 'Brasil', brand: 'Jeep / RAM', plant: 'Goiana, Pernambuco' },
  '94D': { country: 'Brasil', brand: 'Nissan', plant: 'Resende, RJ' },
  '93H': { country: 'Brasil', brand: 'Honda', plant: 'Sumaré, SP' },
  '1HG': { country: 'Estados Unidos', brand: 'Honda', plant: 'Marysville, Ohio' },
  '3VW': { country: 'México', brand: 'Volkswagen', plant: 'Puebla, México' },
  '3FA': { country: 'México', brand: 'Ford', plant: 'Cuautitlán, México' },
  '3FT': { country: 'México', brand: 'Ford', plant: 'Hermosillo, México' },
  '3N1': { country: 'México', brand: 'Nissan', plant: 'Aguascalientes, México' },
  'WBA': { country: 'Alemania', brand: 'BMW', plant: 'Múnich, Alemania' },
  'WVW': { country: 'Alemania', brand: 'Volkswagen', plant: 'Wolfsburg, Alemania' },
  'WAU': { country: 'Alemania', brand: 'Audi', plant: 'Ingolstadt, Alemania' },
  'WDD': { country: 'Alemania', brand: 'Mercedes-Benz', plant: 'Stuttgart, Alemania' }
};

// Tabla de año de modelo (Carácter 10 del VIN)
const VIN_YEAR_TABLE = {
  'A': 2010, 'B': 2011, 'C': 2012, 'D': 2013, 'E': 2014,
  'F': 2015, 'G': 2016, 'H': 2017, 'J': 2018, 'K': 2019,
  'L': 2020, 'M': 2021, 'N': 2022, 'P': 2023, 'R': 2024,
  'S': 2025, 'T': 2026
};

/**
 * Decodifica un número VIN de 17 caracteres.
 */
export function decodeVin(vinRaw) {
  if (!vinRaw) return null;
  const vin = vinRaw.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (vin.length !== 17) {
    return {
      valid: false,
      raw: vin,
      error: `El VIN debe tener exactamente 17 caracteres (detectados: ${vin.length})`
    };
  }

  const wmi = vin.substring(0, 3);
  const wmiInfo = WMI_TABLE[wmi] || { country: 'Desconocido', brand: 'Fabricante Genérico', plant: 'No especificada' };
  
  const yearChar = vin.charAt(9);
  const year = VIN_YEAR_TABLE[yearChar] || 'Año no determinado';

  // Intentar emparejar con un vehículo del catálogo argentino
  const matched = ARGENTINA_VEHICLES.find(v => v.vinPrefix === wmi) || null;

  return {
    valid: true,
    vin,
    wmi,
    country: wmiInfo.country,
    brand: wmiInfo.brand,
    assemblyPlant: wmiInfo.plant,
    modelYear: year,
    serialNumber: vin.substring(11),
    matchedProfile: matched
  };
}
